import setuptools
import os,shutil

#https://stackoverflow.com/questions/24071491/how-can-i-make-a-python-wheel-from-an-existing-native-library
class BinaryDistribution(setuptools.Distribution):
    def has_ext_modules(foo):
        return True



pk = setuptools.find_packages(exclude=['utils'])

print(pk)

dstdir = os.path.dirname(__file__) + "/photonpy/x64/Release"
print(dstdir)
#os.makedirs(dstdir,exist_ok=True)
#shutil.copy(os.path.dirname(__file__)+"/x64/Release/photonpy.dll",dstdir)

setuptools.setup(
    name="photonpy",
    version="1.0.36rc2",
    author="Jelmer Cnossen",
    author_email="j.p.cnossen@tudelft.nl",
    description="CUDA-Based image processing for single molecule localization microscopy",

    url="https://github.com/qnano/photonpy",
    packages=pk,
    #package_data={'smlmlib':['x64/Release/photonpy.dll'] },
	data_files=[('lib/site-packages/photonpy/x64/Release', 
              ['photonpy/x64/Release/photonpy.dll', 
		'photonpy/x64/Release/cudart64_110.dll',
		'photonpy/x64/Release/vcruntime140.dll',
		'photonpy/x64/Release/vcruntime140_1.dll',
        'photonpy/x64/Release/api-ms-win-crt-heap-l1-1-0.dll', 
        'photonpy/x64/Release/api-ms-win-crt-math-l1-1-0.dll', 
        'photonpy/x64/Release/api-ms-win-crt-runtime-l1-1-0.dll', 
        'photonpy/x64/Release/api-ms-win-crt-stdio-l1-1-0.dll', 
        'photonpy/x64/Release/msvcp140.dll'
		])],
    classifiers=[
        "Programming Language :: Python :: 3",
		"Programming Language :: C++",
        "License :: OSI Approved :: MIT License",
        "Operating System :: Microsoft :: Windows"
    ],
    install_requires=[
        'alabaster==0.7.12',
        'appdirs',
        'asciitree==0.3.3',
        'asttokens',
        'attrs',
        'Babel',
        'backcall',
        'backports.functools-lru-cache',
        'bleach==5.0.0',
        'bokeh',
        'brotlipy',
        'cachey',
        'certifi',
        'cffi',
        'charset-normalizer',
        'click',
        'cloudpickle',
        'colorama',
        'commonmark==0.9.1',
        'cryptography',
        'cycler',
        'cytoolz==0.11.2',
        'dask',
        'debugpy',
        'decorator',
        'distributed',
        'docstring-parser',
        'docutils',
        'entrypoints',
        'executing',
        'fasteners',
        'fonttools==4.25.0',
        'freetype-py',
        'fsspec',
        'glrt==1.0.3',
        'h5py==2.10.0',
        'HeapDict==1.0.1',
        'hsluv',
        'idna',
        'imagecodecs',
        'imageio',
        'imagesize',
        'importlib-metadata',
        'importlib-resources',
        'ipykernel',
        'ipython',
        'ipython-genutils==0.2.0',
        'jedi',
        'Jinja2',
        'joblib',
        'jsonschema',
        'jupyter-client',
        'jupyter-core',
        'keyring==23.5.1',
        'kiwisolver',
        'locket',
        'lz4',
        'magicgui',
        'MarkupSafe',
        'matplotlib',
        'matplotlib-inline',
        'mkl-fft==1.3.1',
        'mkl-random',
        'mkl-service==2.4.0',
        'mock',
        'msgpack',
        'munkres==1.1.4',
        'napari',
        'napari-console',
        'napari-plugin-engine',
        'napari-svg',
        'nest-asyncio',
        'networkx',
        'numcodecs',
        'numexpr',
        'numpy',
        'numpydoc',
        'packaging',
        'pandas',
        'parso',
        'partd',
        'photonpy @ git+https://gitlab.com/qnano/simflux3d.git@206c35ca80fbc6c0949f8984cbf609a7b24b2c42',
        'pickleshare',
        'Pillow',
        'Pint',
        'pkginfo==1.8.2',
        'prompt-toolkit',
        'psutil',
        'psygnal',
        'pure-eval',
        'pycparser',
        'pydantic',
        'Pygments',
        'PyOpenGL',
        'pyOpenSSL',
        'pyparsing',
        'PyQt5==5.15.4',
        'PyQt5-sip',
        'pyreadline==2.1',
        'pyrsistent',
        'PySocks',
        'python-dateutil',
        'pytz',
        'PyWavelets',
        'pywin32==303',
        'pywin32-ctypes==0.2.0',
        'PyYAML==5.4.1',
        'pyzmq',
        'qtconsole',
        'QtPy',
        'readme-renderer==35.0',
        'requests',
        'requests-toolbelt',
        'rfc3986',
        'rich',
        'scikit-image',
        'scikit-learn',
        'scipy',
        'seaborn',
        'sip',
        'six',
        'snowballstemmer',
        'sortedcontainers',
        'Sphinx',
        'sphinxcontrib-applehelp==1.0.2',
        'sphinxcontrib-devhelp==1.0.2',
        'sphinxcontrib-htmlhelp',
        'sphinxcontrib-jsmath==1.0.1',
        'sphinxcontrib-qthelp==1.0.3',
        'sphinxcontrib-serializinghtml',
        'stack-data',
        'superqt',
        'tables==3.6.1',
        'tblib',
        'threadpoolctl',
        'tifffile',
        'toml',
        'toolz',
        'torch==1.11.0',
        'torchaudio==0.11.0',
        'torchvision==0.12.0',
        'tornado',
        'tqdm',
        'traitlets',
        'twine==4.0.1',
        'typing_extensions',
        'urllib3',
        'vispy',
        'wcwidth',
        'webencodings==0.5.1',
        'win-inet-pton',
        'wincertstore==0.2',
        'wrapt',
        'ypstruct==0.0.2',
        'zarr',
        'zict',
        'zipp',
    ],
)
